//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
namespace AssemblyCSharp
{
	public class BoidMove : MonoBehaviour {
		public BoidMove(Boid boid, Vector3 a1, Vector3 a2, Vector3 a3, int dt){
			boid.velocity = boid.velocity + a1*dt+a2*dt+a3*dt;
			boid.position = boid.position + boid.velocity;
		}

		void Update () {
			transform.position = new Vector3(transform.position.x + 0.001f, transform.position.y);
		}
	}
}

